apple_resource(
    name='AppResources',
    dirs=[
        'Animations',
        'Fonts',
        'Localizations',
        'Styles',
    ],
    files=[
    ],
    visibility=[
        'PUBLIC'
    ],
)

apple_asset_catalog(
    name='AppAssets',
    app_icon='AppIcon',
    dirs=[
        'Images.xcassets'
    ],
    visibility=[
        'PUBLIC'
    ]
)

export_file(
    name = "BNDLInfo.plist",
    visibility = [
        "PUBLIC"
    ],
)