source 'https://github.com/CocoaPods/Specs'
platform :ios, 9.3
use_frameworks!
plugin 'cocoapods-rome'

abstract_target :Dependencies do

    pod 'RxSwift'
    pod 'RxCocoa'

    target :Empty
end

install! 'cocoapods', integrate_targets: false

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['LD'] = "#{Dir.pwd}/ld.py"
            config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
            config.build_settings['DEFINES_MODULE'] = 'YES'
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
            config.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
