apple_bundle(
    name = "App",
    binary = ":AppBinary",
    extension = "app",
    info_plist = "Info.plist",
    product_name = PROJECT_NAME,
    deps = [
        '//Sources/Core:CoreFramework'
    ],
    visibility = [
        'PUBLIC'
    ],
)

apple_binary(
    name = "AppBinary",
    srcs = glob([
        "*.m"
    ]),
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    deps = [
        '//Resources:AppResources',
        '//Sources/Core:Core'
    ],
)

apple_package(
    name = "AppPackage",
    bundle = ":App",
)
