#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

#brew bundle check &>/dev/null  || brew bundle

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
	brew bundle check >/dev/null 2>&1  || {
		echo "==> Installing Homebrew dependencies…"
		brew bundle
	}
fi

if [ -f "Gemfile" ]; then
	echo "==> Installing gem dependencies…"
	bundle check >/dev/null 2>&1  || {
		bundle install --quiet --without production
	}
fi

cd Dependencies
if [ -f "Podfile" ]; then
	echo "==> Installing pod dependencies…"
	bundle exec pod repo update
	bundle exec pod install
fi