#!/usr/bin/env bash
#
# Resolve all dependencies that the application requires to run.

set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${DIR}/../Dependencies"

[[ -s Brewfile ]] && {
    brew bundle check || brew bundle;
}

[[ -s Gemfile ]] && {
    bundle check || bundle install;
}

#bundle exec pod repo update
[[ -s Podfile ]] && {
    bundle exec pod install
}
