#!/usr/bin/env bash
#
# Fix header comments in source files

set -euo pipefail
IFS=$'\n\t'

cd "${0%/*}/../Sources"

declare NAME='Igor Tarasenko'

#######################################
# Generates header comment
# Globals:
#   NAME
# Arguments:
#   File name
# Returns:
#   header lines
#######################################
header_comment() {
	cat <<- END
	//
	// $1
	// Created by $NAME on $(date +"%d/%m/%y")
	// Copyright © $(date +"%Y") $NAME
	// Licensed under the MIT license, see LICENSE.md file
	//
	END
}

#######################################
# Returns content of files without header comment
# Globals:
#   none
# Arguments:
#   File name
# Returns:
#   content of file
#######################################
content_of_file_without_header() {
	still_comment=true
	while IFS= read -r line; do
		[[ $line =~ ^\/\/.*$ ]] || still_comment=false
		[[ $still_comment == true ]] || echo "$line"
	done < "$1"
	echo "$line"
}

# main function
main() {
	for file in ./**/*.swift; do
		echo "Replacing header in $file"
		echo "$(header_comment ${file##*/})" > "$file".tmp
		echo "$(content_of_file_without_header $file)" >> "$file".tmp
		mv -f "$file".tmp $file
	done
}

main


